TRAIN:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_INFLATE: False
  CHECKPOINT_EPOCH_RESET: True
  MIXUP_ALPHA: 0.0
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 16
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  AUTOAUGMENT: True
  COLORAUGMENT: False
  RANDAUGMENT: False
  RANDOM_FLIP: False
  RAND_CROP: 0.5
  PATH_LABEL_SEPARATOR: ','
XVIT:
  BASE_MODEL: vit_base_patch16_224_in21k
  CONSENSUS_TYPE: 'vit'
  USE_XVIT: True
  SHIFT_DIV: 4
  NUM_SEGMENTS: 16
  LOCATIONS_LIST: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
BN:
  USE_PRECISE_STATS: False
SOLVER:
  BASE_LR: 0.03
  LR_POLICY: cosine
  STEPS: [0,20,40]
  LRS: [1.0,0.1,0.01]
  MAX_EPOCH: 35
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 5.0
  WARMUP_FACTOR: 0.1
  WARMUP_START_LR: 0.003
  OPTIMIZING_METHOD: sgd
  CLIP_GRADIENT: -1.0
MODEL:
  NUM_CLASSES: 174
  ARCH: xvit
  MODEL_NAME: XVIT
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 2
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
